# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'QMotors' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 5.0.0'
  pod 'SideMenu'
  pod 'SwiftMaskText'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'MBProgressHUD', '~> 1.2.0'

end
